Add missing IPython dependency to requirements.txt
Before that, I got:

    from IPython import display
    ModuleNotFoundError: No module named 'IPython'